name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: zulu
          cache: maven
      - run: mvn clean verify -B
      - uses: mddburgess/java-reporter-action@surefire
        if: ${{ always() }}
