name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - run: mvn clean verify -B
      - uses: mddburgess/java-reporter-action@rewrite
        if: ${{ always() }}
        with:
          surefire: required
          pmd: expected
          pmd-report-paths: "**/pmd.json"
          cpd: required
          cpd-report-paths: "**/cpd.json"
          spotbugs: expected
          spotbugs-report-paths: "**/spotbugs.xml"
          checkstyle: required
          checkstyle-report-paths: "**/checkstyle-report.xml"
